### PR TITLE
Update openstreetmap.org URLs to use https

### PR DESCRIPTION
**Pull request by tomhughes**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Hey @tomhughes, how about I transfer this repo to the openstreetmap organization? Less steps in the workflow for both of us if you can just commit changes like this directly.

**Comment by tomhughes** [comment]
@jfirebaugh Sure - feel free to transfer it.

**Comment by jfirebaugh** [comment]
I'm not allowed to:

image

**Comment by tomhughes** [comment]
Hmm I thought I would just get asked to approve it but apparently transfers to organisations are annoyingly different... I think you should be able to do it now.

**Pull request merged**
